### PR TITLE
Produce APIs that comply with the (provisional) JSON API standard.

### PR DESCRIPTION
**Pull request by jfinkels**
This will be a major change to the behavior of Flask-Restless, so it should be postponed until, say a 1.0.0 release. The first commit I've added below adds failing tests for the behavior expected by the [JSON API standard][1].

Further work on this branch will fix many of the issues with discoverability, performance, and unexpected behavior reported in other issues.

[1]: http://jsonapi.org/format/#document-structure-resource-collection-representations

### CODE REVIEW

**Comment by ctolsen** [comment]
I'm new to Flask-Restless, and don't know it well enough yet, but this is some amazing work. I was reading the documentation for some research a while ago, and JSONAPI support was one of the things I expected to have to hack together myself. The rest is exactly what I was looking for.

If the long term goal is to get this merged back in, I would like to offer some help improving and maintaining this in a branch until then.

**Comment by jfinkels** [comment]
Hi @ctolsen! As you can see on this branch, I'm essentially in the middle of rewriting everything, since I'm older and wiser today than when I started this project. In the process of creating JSON API support, I'm rewriting all the code and tests right now (haven't even started on documentation!), so I don't think you can help with this branch quite yet. But if you see something that's wrong, feel free to let me know or fix it. I'll be working on this branch for a while still.

**Comment by jfinkels** [comment]
Actually, there's quite a few tests with ``assert False, 'Not implemented'``, which means I was either too lazy to write a test or too confused to figure out an appropriate test. I would be grateful if someone implemented some of those.

**Comment by ctolsen** [comment]
I'm slowly getting up to speed with the framework in general, so I'll certainly have a look at that once I have my head wrapped around everything a bit better.

**Comment by ctolsen** [comment]
Are you updating this to RC3? I found that there's currently no support for the `linkage` attribute. 

Let me know if you're _not_ in the middle of fixing it and I can have a stab at it.

**Comment by jfinkels** [comment]
Yes, I am working off the most recent version of the JSON-API specification. If you see some place where something is not fully tested, please do add the missing test method and make a pull request (with respect to this `jsonapi` branch). Even better, make a pull request that implements the changes to the code that make the test pass.

Where I really need help is with association proxies and/or many-to-many relationships. There's a bunch of places where there are unimplemented tests, and I simply don't know how to implement them!

**Pull request merged**
