### PR TITLE
Allow clients to specify columns in responses

### PR DESCRIPTION
**Pull request by chaitan94**
Say a request to /api/user returns something similar to this:

    {...
        objects: [
            {"id": 1, "name": "abc", "age": 11},
            {"id": 2, "name": "kbc", "age": 7},
            {"id": 3, "name": "bkc", "age": 17}
        ]..
    }

But you really only wanted 'id' and 'age' fields, this patch allows you to do this:
requesting /api/user?cols=id,age

    {...
        objects: [
            {"id": 1, "age": 11},
            {"id": 2, "age": 7},
            {"id": 3, "age": 17}
        ]..
    }

I though this might help few users (like me) by reducing the data transmitted..
Feedback welcome as this was not tested rigorously and I might have missed something.

### CODE REVIEW

**Comment by ddurieux** [comment]
Hi glyphobet, have you worked to fix the problems?

I'm very interessing to have possibility to define in URL the columns to get/display. I can work on this patch to be integrated into repository ;)

**Comment by glyphobet** [comment]
@ddurieux the work we have done is in our branch, feel free to pull it and work on it.

**Comment by ddurieux** [comment]
Yep, but prefer have it in the official release, because I will offer my application (free software) to people and it's more simple if it's in release of flask-restless ;)

**Comment by roemhildtg** [comment]
Hi all. Was the ability to only return certain columns via a GET request ever added? Perhaps in a different patch?

**Comment by jfinkels** [comment]
Flask-Restless has been rewritten to support the JSON API protocol, so this can be done by having the client use the `fields` query parameter. I apologize for the lack of communication on this!

http://jsonapi.org/format/#fetching-sparse-fieldsets

http://flask-restless.readthedocs.org/en/latest/fetching.html#specifying-which-fields-appear-in-responses

**Pull request closed without merging**
