### PR TITLE
Split DefaultDeserializer._load in smaller structured functions

### PR DESCRIPTION
**Pull request by hasier**
The new Serializer/Deserializer approach makes the code much more reusable, but the DefaultDeserializer is too difficult to override and to change it's behaviour. This changes try to split all its functionality in different smaller and better defined methods, so that it is also easier to inherit and to override how it works.

### CODE REVIEW

**Comment by jfinkels** [comment]
Wonderful! I'll take a look at this and play around with it a bit.

If you're interested in these sort of code changes, and want to help out with new pull requests, I have two more ideas in the same vein:

- do the same sort of thing for the serializer class
- a "partial deserializer" that handles the case of updating a resource (on PATCH requests),

(PS the build for this pull request is currently failing, you may want to give it another look.)

**Comment by hasier** [comment]
Oh true, I have fixed it (should work now, otherwise will check again :P )
I have also split the DefaultRelationshipDeserializer, think it can be helpful too.
Regarding the Serializer, I might also take a look if you think these changes are good to go, we'll see :)

**Comment by jfinkels** [comment]
This is a good start, but there are some improvements to be made here. First, there is some obvious refactoring that can be done between the two classes: for one example, the `get_model_from_data` method seems to be identical in the two classes. That should go in a common base class. Some other easier changes:

- `cleanup_input_data` is a misleading name because 1) "cleanup" implies some cleanup after the work is already done, and 2) it is more than just cleaning data, it is extracting the resource,
- Docstrings should follow [PEP 257][1] in addition to PEP8; also, I generally don't use the `:param whatever:` notation, I just described the arguments in prose (like in the official Python documentation).

[1]: https://www.python.org/dev/peps/pep-0257/

**Comment by jfinkels** [comment]
I've implemented this in pull request #618. If you have any other suggestions please add them there.

**Pull request closed without merging**
