### PR TITLE
convert datetime and uuid objects in attributes dict

### PR DESCRIPTION
**Pull request by chaoflow**

### CODE REVIEW

**Comment by chaoflow** [comment]
@jfinkels Does it make sense that I'm porting this fix to the latest jsonapi?

**Comment by jfinkels** [comment]
This should be fixed in the development version (see https://github.com/jfinkels/flask-restless/blob/master/flask_restless/serialization.py#L381).

**Comment by chaoflow** [comment]
uuid.UUID objects seem not to be handled, yet in master and in the jsonapi branch neither uuid.UUID nor datetime.* objects are handled.

My pull request was for the jsonapi branch.

**Comment by jfinkels** [comment]
I have merged the jsonapi branch into master, and added a test for serializing non-primary key UUID fields. See `test_serialize_uuid` in `tests/test_fetching.py`. Can you give a minimal working example that demonstrates the failure?

**Comment by jfinkels** [comment]
The tests for serializing UUID, date, time, and datetime objects now live in the file `test_serialization.py`. The serialization now lives at https://github.com/jfinkels/flask-restless/blob/master/flask_restless/serialization.py#L532.

Is this still an issue?

**Comment by jfinkels** [comment]
I added more tests for this in pull request #531, I believe it to be fixed.

**Pull request closed without merging**
