### PR TITLE
Explicit declaration of exposed sub-resources.

### PR DESCRIPTION
**Pull request by dnordberg**
Enables explicit declaration of exposed model sub-resources by
passing a `relationname` parameter to the `APIManager.create_api`
method.

This enables model relation endpoints to declare their own include and
exclude rules, methods, and post and pre processors.

If relationname is not passed to `create_api`, only the primary model
endpoints are created (e.g. /api/person, /api/person/1) you won't be
able to access other endpoints. Additional calls to `create_api` which
include the `relationname` parameter create the relation endpoints and
at this point include and exclude rules as well as post and pre
processors can be passed (Same as the primary model or different).

This also enables filtering of exposed relations using the same API.

This introduces two backwards incompatible changes.

1) Each exposed relation endpoint needs to be defined using `create_api`
   and passing the `relationname` parameter.

2) When passing `exclude_columns`, if you wish to exclude all relational data
   in a field, you only need to pass the field name, and not each field
   under the relation. For example,

   ```exclude_columns = ['country']```

   Instead of

   ```exclude_columns = ['country.name', 'country.code']```

This commit also updates the `has_field` doc string, which should also work
for `hybrid_property` fields.

An example declaration exposing a primary resource and a sub-resource:

```
apimanager.create_api(Country,
        methods=methods,
        url_prefix="/api/v1",
        results_per_page=results_per_page,
        max_results_per_page=100000,
        postprocessors=postprocessors_,
        preprocessors=preprocessors_,
        allow_functions=allow_functions,
        exclude_columns=[],
        include_columns=[],
        validation_exceptions=[ValidationError,
            ProcessingException,
            BadRequest],
        )

apimanager.create_api(Country,
        relationname='cities',
        methods=methods,
        url_prefix="/api/v1",
        results_per_page=results_per_page,
        max_results_per_page=100000,
        postprocessors=postprocessors_,
        preprocessors=preprocessors_,
        allow_functions=allow_functions,
        exclude_columns=[],
        include_columns=[],
        validation_exceptions=[ValidationError,
            ProcessingException,
            BadRequest],
        )
```

### CODE REVIEW

**Comment by drmclean** [comment]
Please may we have an update on the status of this merge? 

I'm in fairly desperate need of the ability to define explicit relational endpoints but cannot risk patching my local copies of flask-restless and having problems later on if an update conflicts with my patch. 

Failing a merge with this branch could someone advise me on how to proceed if I want to have this functionality but need the build to be reliable and robust to future merges?

**Comment by dnordberg** [comment]
I suspect a lot of work would be needed to bring this up to date with master. Also, not sure if will get merged since it’s doesn’t seem to be on the road map.

**Comment by drmclean** [comment]
Thanks for the message and for maintaining this project, can you offer me any advice on what to actually do about my problem? I seem to be stuck in a corner. 

I do want to have the power to have relational endpoints like `product/{id}/owner`
which will return the data of the `owner` of the `product` with `id={id}` but if I use the current system then such an endpoint will be extremely slow perhaps prohibitively slow. I can't filter out the extraneous data either since all the logic is wrapped up inside `create_api`. 

I don't want to write each endpoint manually since there are an exponentially increasing number of them a I go through the layers!

I don't want to include the patch as it might cause problems later. 

Have you any suitable suggestions for how I might make a suitable solution?

**Comment by dnordberg** [comment]
>> I do want to have the power to have relational endpoints like product/{id}/owner
which will return the data of the owner of the product with id={id} but if I use the current system then such an endpoint will be extremely slow perhaps prohibitively slow. 

This patch does nothing to help performance in this case, at best if allows sub-relations to define fields to include, exclude in the output.

>> I can't filter out the extraneous data either since all the logic is wrapped up inside create_api.

If you wish to use flask-restless master, perhaps a postprocessor might help in reducing data sent to the client?

>> I don't want to write each endpoint manually since there are an exponentially increasing number of them a I go through the layers!

This branch may not work for you then since its intent is to force '*explicit* declaration of exposed sub-resources' vs flask-restless master which given a resource, exposes all sub-resources.

**Comment by drmclean** [comment]
> This patch does nothing to help performance in this case, at best it allows sub-relations to define fields to include, exclude in the output.

This seems to be saying that if I have a model with a vary large number of child relations (for example a `company` with a large number of `customers` then my system will get slower and slower as the number of `customers` increases, regardless of whether I actually include them when performing a GET on the company. Have I misunderstood? 

I think my questions are going way beyond the scope of this thread but I can't find much information about Flask-Restless performance online. Is there an IRC or mailing list that I can post questions to?

> If you wish to use flask-restless master, perhaps a postprocessor might help in reducing data sent to the client?

mnnn that is actually kinda obvious now you mention...

**Comment by dnordberg** [comment]
> This seems to be saying that if I have a model with a vary large number of child relations (for example a company with a large number of customers then my system will get slower and slower as the number of customers increases, regardless of whether I actually include them when performing a GET on the company. Have I misunderstood?

No, for deep relations, if its specified as excluded it wont be fetched and you get no performance penalty.

**Comment by drmclean** [comment]
ahh so the patch doesn't change the fact that sub-relation endpoints are getting more data than they should, it just doesn't present that data to the user?

**Comment by dnordberg** [comment]
Yes, except if a foreign keys or relations is in the exclude list, its related records wont be fetched. Same for flask-restless master I believe.

The patch does allow filtering over sub-resources though, which I don't think master does (At least not at the time of creating the patch).

**Comment by jfinkels** [comment]
I have made too many changes for this to be relevant anymore, I'm sorry about not updating you sooner! I believe at least some of the issues that this pull request intended to solve have been fixed in the development version of Flask-Restless, since we follow the JSON API specification now. There are still some issues, such as serialization being attached to the base model and not the actual requested model; see issue #475.

**Pull request closed without merging**
